### ISSUE TITLE
create a decorator to process the json and txt data.

### ISSUE THREAD

**Issue by mmaleki92** [advanced-python-mft/advanced_2#2]
فرض کنید که دیتایی داشته باشید که می‌تواند `json` یا `.txt` را بخواند به این صورت که اسم فایل به فانکشن داده می‌شود:

```python
def fun():
    ...

fun(file_name)
```
و تمام خطوط عددی فایل را بخواند، این کار را با decorator انجام دهید.

**Comment by ashkan0201** [comment]
python
